#ifndef JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_H
#define JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_H

#include <string>

std::string generate_phrase();

#endif //JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_H
