#ifndef JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_LIBRARY_H
#define JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_LIBRARY_H

#include <string>

extern "C" auto generate_phrase() -> const char*;

#endif // JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_LIBRARY_H
