#ifndef JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_LIBRARY_H
#define JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_LIBRARY_H

#include <string>

auto generate_phrase() -> std::string;

#endif // JARGON_GENERATOR_RANDOM_JARGON_GENERATOR_LIBRARY_H
